### ISSUE TITLE
[Bug] Unable to store the passcode

### ISSUE THREAD

**Issue by aliawe** [XRPL-Labs/XUMM-Issue-Tracker#274] opened 2020-10-14 18:17 UTC
Error 
Unable to store the passcode.this should not happen. A bug report was sent to the xumm support team. Please contact us at support@xumm.app for more information .
At the first I want type passcode 6 word  and I enforced this problem.

**Comment by WietseWind** [comment] 2020-10-15 07:39
Hey! Thank you for reporting! Are you on iOS or Android? And did you perhaps:

[] Update your phone / OS
[] Change phones and migrated data / recovered a backup?

And what's your phone brand and model and OS version?

This info would help us a lot 👍 

Thanks,
@N3TC4T, @WietseWind + team

**Comment by aliawe** [comment] 2020-10-15 08:23
My phone is Samsung note 5 and Android 7

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 15, 2020 at 11:09 AM, Wietse Wind<notifications@github.com> wrote:   


Hey! Thank you for reporting! Are you on iOS or Android? And did you perhaps:

[ ] Update your phone / OS
[ ] Change phones and migrated data / recovered a backup?

And what's your phone brand and model and OS version?

This info would help us a lot 👍
 
Thanks,
@N3TC4T, @WietseWind + team

**Comment by N3TC4T** [comment] 2020-10-15 12:14
@aliawe Thanks for the report, we have seen this issue before on android device's with version <= 7, but we couldn't reproduce the bug so we added extra crash report to the app and now we know where is the problem and will be fix in the next release, thanks for your report.

**Comment by aliawe** [comment] 2020-10-15 18:14
Next update , when release? 

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 15, 2020 at 3:44 PM, N3TC4T<notifications@github.com> wrote:   


@aliawe Thanks for the report, we have seen this issue before on android device's with version <= 7, but we couldn't reproduce the bug so we added extra crash report to the app and now we know where is the problem and will be fix in the next release, thanks for your report.

**Comment by WietseWind** [comment] 2020-10-16 11:07
@N3TC4T 😇

**Comment by N3TC4T** [comment] 2020-10-19 11:57
some fixes already applied to the app and it's will be included in the next release

https://github.com/XRPL-Labs/XUMM-App/pull/39/commits/394f0f5771b9043627d30ebaf5ec0c728c593a77

I'm not sure when we release the next version but we try to do it ASAP 👍

**Comment by aliawe** [comment] 2020-10-22 07:41
I'll want active spark token .please provide new update until 12 December.  Thanks 🙏

**Comment by N3TC4T** [comment] 2020-10-27 09:20
@aliawe The new closed beta release is available right now, if you willing to test the app please contact us using chat option in the XUMM support website, after providing your google play email address, we can add you to the closed beta tester list and you can update the app to the newest release.

https://support.xumm.app/en/

**Closed** 2020-11-03 21:10 UTC
Labels: App, PRIO1
