### ISSUE TITLE
No Prompt for passcode when Xumm Starts

### ISSUE THREAD

**Issue by NetScr1be** [XRPL-Labs/XUMM-Issue-Tracker#308] opened 2021-02-08 04:35 UTC
Opened from [Ticket# 10118](https://xumm.zendesk.com/agent/#/tickets/10118)

**Describe the bug**

Under particular conditions, Xumm sometimes doesn't prompt for the Passcode. Once it stops prompting it won't prompt again until the phone is rebooted.

_N.B. This was reported once only by one user_

**To Reproduce**

1. power on phone
2. Starting XUMM
3. XUMM required me to enter the PIN.
4. Stop XUMM via Overview button
5. Restart XUMM: No PIN request.

**Expected behavior**

Xumm is supposed to prompt for passcode every time on startup

**Screenshots**

Client has video they will add when the issue link is available

### Environment

What build of XUMM are you running? 

* XUMM version: [Pending]

What device are you running XUMM on?

* Manufacturer: [Samsung]
* Model: [Galaxy A10]
* OS version: [Android Version 10]
* Platforms
  * [ ] iOS
  * [X] Android

### Additional context
Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by WietseWind** [comment] 2021-02-08 06:04
Thanks @NetScr1be - duplicate of https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/304 so I'm closing this one

**Closed by WietseWind** 2021-02-08 06:04 UTC
Labels: App, Reported bug
