### ISSUE TITLE
Unable to delete a Xumm (Tangem) card account on XRPoolkit

### ISSUE THREAD

**Issue by WillXUMM** [XRPL-Labs/XUMM-Issue-Tracker#443] opened 2023-08-01 04:57 UTC
1) Sign into XRPtoolkit with card account.
2) Go to Account -> Properties -> Delete account (In XRPtoolkit)
3) You get this screen:
![image](https://github.com/XRPL-Labs/XUMM-Issue-Tracker/assets/79937181/f7e44a66-8871-4780-bae5-3d040400bc2e)
4) Then this one:
![image](https://github.com/XRPL-Labs/XUMM-Issue-Tracker/assets/79937181/778e088b-8832-467d-bb9d-e5bd913b6d0b)
5) Then scan the card
6) Xumm says:
![image](https://github.com/XRPL-Labs/XUMM-Issue-Tracker/assets/79937181/c74194c7-812b-47a1-b138-c3964521f2cf)
6) Xrptoolkit says:
![image](https://github.com/XRPL-Labs/XUMM-Issue-Tracker/assets/79937181/a20613fe-448f-43ec-8d93-821b37a9581d)
7)Xumm says:
![image](https://github.com/XRPL-Labs/XUMM-Issue-Tracker/assets/79937181/a3c3574c-b9ef-48cf-b4cf-448fda9bb0a1)
8) The account is not deleted.

**Comment by WietseWind** [comment] 2023-08-01 05:02
Duplicate of (caused by) #442 

The 7. in your report is something else btw:

 assume the step before you used the "Open in XUMM" button on the XRPToolkit page

Which opened the payload

Then you resolved the payload (signed) 

And then you opened the push notification that was sent in the first place, making tapping the "open in Xumm" button unnecessary 

You tried to open the already resolved payload from the push notification again, but it was already resolved

This is an XRPToolkit thing: they already know (from the payload response) a push was sent

So they shouldn't offer the "open" button

OR

we should clear the push if the attached payload is resolved

Which we tried but doesn't work on Android, so we skipped it till Android supports that to prevent inconsistent behaviour for iOS vs Android users

**Closed by WietseWind** 2023-08-01 05:02 UTC
