### ISSUE TITLE
[Bug] Hide/Show balance icon does not bring the Account address back

### ISSUE THREAD

**Issue by gnurag** [XRPL-Labs/XUMM-Issue-Tracker#280] opened 2020-10-30 03:27 UTC
**Describe the bug**
Hide/Show balance icon does not bring the account address back. On clicking the open-eye icon to hide balance, everything is hidden as expected. Subsequently, on clicking the closed-eye icon to show everything, balances show up but the account address field turns blank.

Further, I wonder what is the purpose of hiding account address. IOU addresses are not hidden via this feature, so it looks like this part needs a rethink. Either hide all account address, including IOUs, or don't hide them. Even though the IOU address is partially shown, `rhub...F3wq` is enough to guess this is a Gatehub IOU.

**To Reproduce**
1. Go to home screen.
2. Verify that the account address shows correctly
3. Click on open-eye icon to hide fields
4. Verify that the account address, XRP balance and IOU balances are hidden
5. Click on closed-eye icon to show fields
6. Verify that the XRP balance and IOU balances are shown again
7. But account address field turns blank 

**Expected behavior**
Account address field should show up again

**Screenshots**
Before
![xumm-eye-closed](https://user-images.githubusercontent.com/13650/97656365-5133eb00-1a8d-11eb-9a9b-5ab8b24548c3.jpg)

After
![xumm-eye-open](https://user-images.githubusercontent.com/13650/97656381-5a24bc80-1a8d-11eb-913e-0e49e7a8b265.jpg)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.5.2.3146232

What device are you running XUMM on?

* Manufacturer: OnePlus
* Model: 7
* OS version: 
* Platforms
  * [ ] iOS
  * [x] Android

**Comment by WietseWind** [comment] 2020-10-30 07:15
@gnurag Thank you big time! We received another message about this but we couldn't really reproduce (language barrier). This is really helpful!!

**Comment by WietseWind** [comment] 2020-10-30 07:17
Possibly: duplicate of #275

**Closed** 2020-11-03 21:10 UTC
Labels: App, PRIO1, Reported bug
